# Generated by Django 5.0.1 on 2024-02-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_cust_testdrive'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_testdrive',
            name='car_model',
            field=models.CharField(default='Model Name', max_length=100),
        ),
    ]
