# Generated by Django 5.0.1 on 2024-02-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_financing'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmiModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodcode', models.IntegerField(default='50')),
                ('bodytype', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('LA', 'Limousine A200'), ('SGLA', 'SUV GLA220d 4Matic'), ('LC', 'Limousine C200'), ('SGLB', 'SUV GLB'), ('SEQB', 'SUV EQB350 4Matic'), ('LE', 'Limousine E220d'), ('SGLC', 'SUV GLC300 4Matic'), ('AMG', 'AMG SL55 4Matic + Roadster'), ('LM', 'Limousine Maybach S680 4Matic'), ('LEQS', 'Limousine EQS580 4Matic'), ('SM', 'SUV Maybach GLS600 4Matic'), ('SGLE', 'SUV GLE300d 4Matic'), ('SGLS', 'SUV GLS450 4Matic'), ('SEQE', 'SUV EQE500 4Matic'), ('LS', 'Limousine S350d ')], max_length=4)),
                ('car_price', models.IntegerField(default='1000')),
                ('down_payment', models.IntegerField(default='1000')),
                ('fin_amount', models.IntegerField(default='1000')),
                ('interest_rate', models.IntegerField(default='5')),
                ('tenure_years', models.IntegerField(default='5')),
            ],
        ),
    ]
