# Generated by Django 5.0.1 on 2024-02-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_emimodels_emi'),
    ]

    operations = [
        migrations.AddField(
            model_name='emimodels',
            name='image',
            field=models.ImageField(default='https://emifreecar.com/images-new/offcer-coming-soon.jpg', upload_to='EmiModels'),
        ),
    ]
