# Generated by Django 5.0.1 on 2024-02-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_emimodels_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodshop_code', models.IntegerField(default='80')),
                ('car_body', models.CharField(default='CarBody', max_length=100)),
                ('modelname', models.CharField(max_length=100)),
                ('description', models.TextField(default='Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor corrupti numquam suscipit itaque voluptas non ea voluptatibus assumenda aspernatur at tempora deserunt, velit quam, ex asperiores provident nisi. Minus, unde!')),
                ('fuel_type', models.CharField(default='fuel', max_length=20)),
                ('kW', models.CharField(default='1', max_length=10)),
                ('image', models.ImageField(default='https://emifreecar.com/images-new/offcer-coming-soon.jpg', upload_to='ShopOnline')),
                ('price', models.IntegerField(default='1000')),
                ('monthly_emi', models.IntegerField(default='1000')),
            ],
        ),
    ]
