# Generated by Django 5.0.1 on 2024-02-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_shoponline'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoponline',
            name='down_payment',
            field=models.IntegerField(default='1000'),
        ),
        migrations.AddField(
            model_name='shoponline',
            name='fin_amount',
            field=models.IntegerField(default='1000'),
        ),
        migrations.AddField(
            model_name='shoponline',
            name='tenure_months',
            field=models.IntegerField(default='48'),
        ),
    ]
