# Generated by Django 5.0.1 on 2024-02-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_shoponline_down_payment_shoponline_fin_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emimodels',
            name='category',
            field=models.CharField(choices=[('LA', 'Limousine A200'), ('SGLA', 'SUV GLA220d 4Matic'), ('LC', 'Limousine C200'), ('SGLB', 'SUV GLB'), ('SEQB', 'SUV EQB350 4Matic'), ('LE', 'Limousine E220d'), ('SGLC', 'SUV GLC300 4Matic'), ('AMG', 'AMG SL55 4Matic + Roadster'), ('LM', 'Limousine Maybach S680 4Matic'), ('LEQS', 'Limousine EQS580 4Matic'), ('SM', 'SUV Maybach GLS600 4Matic'), ('SGLE', 'SUV GLE300d 4Matic'), ('SGLS', 'SUV GLS450 4Matic'), ('SEQE', 'SUV EQE500 4Matic'), ('LS', 'Limousine S350d '), ('AMGC', 'AMG C 43 4Matic')], max_length=4),
        ),
    ]
