# Generated by Django 5.0.1 on 2024-03-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_emimodels_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_testdrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(default='Mr/Mrs./Ms.', max_length=50)),
                ('firstname', models.CharField(default='First Name', max_length=200)),
                ('lastname', models.CharField(default='Last Name', max_length=200)),
                ('email', models.EmailField(default='Email', max_length=300)),
                ('MobileNo', models.IntegerField(default='1234')),
            ],
        ),
    ]
