# Generated by Django 5.0.1 on 2024-03-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_shop_testdrive'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_testdrive',
            name='carmodel',
            field=models.CharField(default='Mercedes Limousine A200', max_length=300),
        ),
    ]
