# Generated by Django 5.0.1 on 2024-03-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='city', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(default='state', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='pincode',
            field=models.IntegerField(default='000000'),
        ),
    ]
