# Generated by Django 5.0.1 on 2024-03-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
                ('satisfied', models.CharField(default='satisfied', max_length=200)),
                ('recommend', models.CharField(default='recommend', max_length=200)),
            ],
        ),
    ]
