# Generated by Django 5.0.1 on 2024-03-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_feedback_satisfied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile.png', upload_to='profile_pictures'),
        ),
    ]
